### ISSUE TITLE
Session Keep getting expired

### ISSUE THREAD

**Issue by Script-Kiddie-JKB** [amosayomide05/chatgpt-whatsapp-bot#4] opened 2022-12-10 10:38 UTC
Session of Chatgpt Keeps on changing so added cookies in env gets expired

![image](https://user-images.githubusercontent.com/78461084/206851070-4a40a5f1-a140-44d6-920f-22ab8884adcf.png)

**Comment by amosayomide05** [comment] 2022-12-13 23:43
Duplicate of #1

**Closed** 2022-12-13 23:44 UTC
